theme: jekyll-theme-minimal
title: Ivan Kuria
description: Dynamic software and cloud Solutions Architect with 7+ years of experience in software security engineering, cloud architecture, and DevSecOps.
