#########################################################################################################################
# --- Required options --- #
#########################################################################################################################

# Name of Website
title: Ivan Kuria

# Name to show in the footer
author: Ivan Kuria

#########################################################################################################################
# --- List of links in the navigation bar --- #
#########################################################################################################################

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: ""

#########################################################################################################################
# --- Logos --- #
#########################################################################################################################

avator: "/assets/img/avator-icaon.png"

round-avator: true

#########################################################################################################################
# --- Footer Social media links --- #
#########################################################################################################################

social-network-links:
  email: your-email@example.com
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  github: daattali
  twitter: daattali
  patreon: DeanAttali
  youtube: "@daattali"
  whatsapp: 15551212
